import {NextResponse} from 'next/server';import {sql} from '../../../lib/db';import {getCurrentUser} from '../../../lib/auth';
const can=(role,allowed)=>allowed.includes(role);
export async function POST(r){const u=await getCurrentUser();if(!u)return NextResponse.json({error:'UNAUTHORIZED'},{status:401});const x=await r.json();try{
 if(x.type==='seller'){if(!can(u.role,['ADMIN','MANAGER']))throw new Error('FORBIDDEN');const a=await sql`insert into sellers(name,contact_name,phone,email) values(${x.name},${x.contact||null},${x.phone||null},${x.email||null}) returning *`;return NextResponse.json(a[0])}
 if(x.type==='product'){if(!can(u.role,['ADMIN','MANAGER','RECEIVER']))throw new Error('FORBIDDEN');const a=await sql`insert into products(seller_id,sku,name,wb_barcode,vendor_code) values(${x.seller_id},${x.sku},${x.name},${x.barcode||null},${x.vendor||null}) returning *`;return NextResponse.json(a[0])}
 if(x.type==='receipt'){if(!can(u.role,['ADMIN','MANAGER','RECEIVER']))throw new Error('FORBIDDEN');const no=x.receipt_no||('RCV-'+Date.now().toString().slice(-8));const a=await sql`insert into receipts(receipt_no,seller_id,status,received_by,notes) values(${no},${x.seller_id},'OPEN',${u.id},${x.notes||null}) returning *`;return NextResponse.json(a[0])}
 if(x.type==='receiveBox'){if(!can(u.role,['ADMIN','MANAGER','RECEIVER']))throw new Error('FORBIDDEN');const code=x.box_code||('BOX-'+Date.now().toString().slice(-9));const a=await sql`select wms_receive_box(${x.seller_id},${x.receipt_id||null},${code},${x.barcode||code},${u.id},${x.notes||null}) id`;return NextResponse.json({id:a[0].id,box_code:code})}
 if(x.type==='setBoxItem'){if(!can(u.role,['ADMIN','MANAGER','RECEIVER']))throw new Error('FORBIDDEN');await sql`select wms_set_box_item(${x.box_id},${x.product_id},${Number(x.qty)},${u.id})`;return NextResponse.json({ok:true})}
 if(x.type==='moveBox'){if(!can(u.role,['ADMIN','MANAGER','RECEIVER','PICKER','PACKER']))throw new Error('FORBIDDEN');await sql`select wms_move_box(${x.box_id},${x.zone_id||null},${x.cell_id||null},${u.id},${x.reason||'Перемещение'})`;return NextResponse.json({ok:true})}
 if(x.type==='order'){if(!can(u.role,['ADMIN','MANAGER']))throw new Error('FORBIDDEN');const no=x.order_no||('ORD-'+Date.now().toString().slice(-9));const a=await sql`select wms_create_order(${no},${x.seller_id},${x.priority||'NORMAL'},${x.deadline||null},${JSON.stringify(x.items||[]) }::jsonb,${u.id}) id`;return NextResponse.json({id:a[0].id,order_no:no})}
 if(x.type==='pick'){if(!can(u.role,['ADMIN','MANAGER','PICKER']))throw new Error('FORBIDDEN');await sql`select wms_pick_order_item(${x.order_item_id},${x.box_id},${Number(x.qty)},${u.id})`;return NextResponse.json({ok:true})}
 if(x.type==='advanceOrder'){if(!can(u.role,['ADMIN','MANAGER','PACKER']))throw new Error('FORBIDDEN');await sql`select wms_advance_order(${x.order_id},${x.target},${u.id})`;return NextResponse.json({ok:true})}
 if(x.type==='user'){if(u.role!=='ADMIN')throw new Error('FORBIDDEN');const a=await sql`insert into users(email,name,password_hash,role,active) values(${x.email.toLowerCase()},${x.name},crypt(${x.password},gen_salt('bf')),${x.role},true) returning id,email,name,role,active`;return NextResponse.json(a[0])}
 if(x.type==='toggleUser'){if(u.role!=='ADMIN')throw new Error('FORBIDDEN');await sql`update users set active=${!!x.active} where id=${x.id}`;return NextResponse.json({ok:true})}
 return NextResponse.json({error:'UNKNOWN_ACTION'},{status:400});
 }catch(e){const m=String(e.message||e);return NextResponse.json({error:m},{status:m==='FORBIDDEN'?403:400})}}
