'use client';
import {useEffect,useMemo,useRef,useState} from 'react';

const NAV=['Обзор','Скан','Приёмка','Короба','Товары','Клиенты','Заказы','Устройства','Сотрудники','Журнал'];
const MOBILE=['Обзор','Скан','Приёмка','Короба','Заказы'];

async function api(url,opts={}){
  const r=await fetch(url,{cache:'no-store',headers:{'content-type':'application/json',...(opts.headers||{})},...opts});
  const j=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(j.error||'Ошибка');
  return j;
}

export default function WmsAppV2(){
  const [state,setState]=useState({loading:true});
  const [tab,setTab]=useState('Обзор');
  const [toast,setToast]=useState('');
  const [modal,setModal]=useState(null);
  const [q,setQ]=useState('');
  async function load(){try{setState({loading:true});setState(await api('/api/bootstrap'))}catch(e){setState({loading:false,error:e.message})}}
  useEffect(()=>{load()},[]);
  async function refresh(msg){await load();if(msg){setToast(msg);setTimeout(()=>setToast(''),1800)}}
  if(state.loading)return <div className="content">Загрузка WMS…</div>;
  if(state.error)return <div className="content"><div className="notice danger">{state.error}</div></div>;
  if(state.setupRequired)return <Auth setup done={load}/>;
  if(!state.user)return <Auth done={load}/>;
  const d=state.data||{};
  const boxes=(d.boxes||[]).filter(x=>`${x.box_code} ${x.seller_name||''} ${x.zone_name||''} ${x.cell_code||''}`.toLowerCase().includes(q.toLowerCase()));
  const visible=tab==='Сотрудники'&&state.user.role!=='ADMIN'?'Обзор':tab;
  return <div className="app">
    <aside className="side">
      <div className="brand">FULFILLMENT <span>WMS</span></div>
      <div className="nav">{NAV.filter(x=>x!=='Сотрудники'||state.user.role==='ADMIN').map(x=><button key={x} className={visible===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div>
      <div className="device" style={{position:'absolute',bottom:20,left:22}}>● ONLINE<br/>{state.user.name}<br/>{state.user.role}</div>
    </aside>
    <main className="content">
      <div className="top"><div><div className="muted">FULFILLMENT CONTROL CENTER</div><h1>{visible}</h1><div className="muted">FBS · ТСД · телефон · единая база</div></div><div className="actions"><button className="btn primary" onClick={()=>setTab('Скан')}>Сканировать</button><button className="btn" onClick={async()=>{await api('/api/auth/logout',{method:'POST'});load()}}>Выйти</button></div></div>
      {toast&&<div className="notice ok">{toast}</div>}
      <div className="grid4"><Metric n="Коробов" v={d.boxes?.length||0}/><Metric n="SKU" v={d.products?.length||0}/><Metric n="Заказов" v={d.orders?.length||0}/><Metric n="Задач" v={(d.tasks||[]).filter(x=>x.status!=='DONE').length}/></div>
      {visible==='Обзор'&&<Overview d={d} setTab={setTab}/>} 
      {visible==='Скан'&&<Scanner onDone={refresh}/>} 
      {visible==='Приёмка'&&<Receiving d={d} done={refresh}/>} 
      {visible==='Короба'&&<Boxes d={d} rows={boxes} q={q} setQ={setQ} open={setModal}/>} 
      {visible==='Товары'&&<Products d={d} done={refresh}/>} 
      {visible==='Клиенты'&&<Clients d={d} done={refresh}/>} 
      {visible==='Заказы'&&<Orders d={d} done={refresh}/>} 
      {visible==='Устройства'&&<Devices d={d} done={refresh}/>} 
      {visible==='Сотрудники'&&<Users d={d} done={refresh}/>} 
      {visible==='Журнал'&&<Audit d={d}/>} 
    </main>
    <nav className="mobilebar">{MOBILE.map(x=><button key={x} className={visible===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
    {modal&&<BoxModal spec={modal} d={d} close={()=>setModal(null)} done={async m=>{setModal(null);await refresh(m)}}/>}
  </div>
}

function Metric({n,v}){return <div className="metric"><small>{n}</small><b>{v}</b></div>}

function Auth({setup,done}){const[f,setF]=useState({name:'',email:'',password:''}),[err,setErr]=useState('');async function go(){try{await api(setup?'/api/auth/setup':'/api/auth/login',{method:'POST',body:JSON.stringify(f)});done()}catch(e){setErr(e.message)}}return <div style={{maxWidth:420,margin:'70px auto',padding:16}}><div className="card"><h2>{setup?'Первичная настройка':'Вход в WMS'}</h2>{setup&&<input placeholder="Имя администратора" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/>}<input placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input type="password" placeholder="Пароль" value={f.password} onChange={e=>setF({...f,password:e.target.value})} onKeyDown={e=>e.key==='Enter'&&go()}/>{err&&<div className="notice danger">{err}</div>}<button className="btn primary" style={{width:'100%'}} onClick={go}>{setup?'Создать администратора':'Войти'}</button></div></div>}

function Overview({d,setTab}){const stages=[['Приёмка','RCV'],['QC','QC'],['Сортировка','SRT'],['Хранение','STG'],['Picking','PCK'],['Packing','PAK'],['Готово','RDY'],['Отгрузка','SHP']];return <div className="cards"><section className="card"><h3>Операционный поток</h3><div className="flow">{stages.map(([n,c])=><button className="step" key={c} onClick={()=>setTab(c==='RCV'?'Приёмка':c==='PCK'||c==='PAK'||c==='RDY'||c==='SHP'?'Заказы':'Короба')}><b>{n}</b><span className="muted">{(d.boxes||[]).filter(x=>x.zone_code===c).length} коробов</span></button>)}</div></section><section className="card"><h3>Быстрый старт</h3><button className="btn primary" style={{width:'100%',margin:'4px 0'}} onClick={()=>setTab('Скан')}>Открыть сканер</button><button className="btn" style={{width:'100%',margin:'4px 0'}} onClick={()=>setTab('Приёмка')}>Принять короб</button><button className="btn" style={{width:'100%',margin:'4px 0'}} onClick={()=>setTab('Заказы')}>Picking / Packing</button></section></div>}

function Scanner(){
  const [code,setCode]=useState('');const[res,setRes]=useState(null);const[cam,setCam]=useState(false);const video=useRef(null);const controls=useRef(null);
  async function lookup(v=code){const val=String(v||'').trim();if(!val)return;try{const r=await api('/api/scan',{method:'POST',body:JSON.stringify({barcode:val})});setRes(r);setCode('')}catch(e){setRes({error:e.message})}}
  useEffect(()=>{if(!cam)return;let stopped=false;async function start(){try{const {BrowserMultiFormatReader}=await import('@zxing/browser');const reader=new BrowserMultiFormatReader();controls.current=await reader.decodeFromVideoDevice(undefined,video.current,(result)=>{if(result&&!stopped){const text=result.getText();stopped=true;controls.current?.stop();setCam(false);lookup(text)}})}catch(e){setRes({error:'Не удалось запустить камеру: '+e.message});setCam(false)}}start();return()=>{stopped=true;controls.current?.stop()}},[cam]);
  return <section className="card"><h3>Скан-центр</h3><div className="notice">ТСД: режим HID/Keyboard, штрихкод завершается Enter. Телефон: камера работает через ZXing и HTTPS.</div><div className="scanbox"><input autoFocus value={code} placeholder="BOX / SKU / ячейка / заказ" onChange={e=>setCode(e.target.value)} onKeyDown={e=>e.key==='Enter'&&lookup()}/><div className="actions" style={{marginTop:8}}><button className="btn primary" onClick={()=>lookup()}>Распознать</button><button className="btn" onClick={()=>setCam(v=>!v)}>{cam?'Закрыть камеру':'Камера телефона'}</button></div>{cam&&<video ref={video} className="camera" playsInline muted/>}{res&&<div className={`notice ${res.error?'danger':'ok'}`} style={{marginTop:10}}>{res.error?res.error:<><b>{res.kind}: {res.code}</b><br/>{res.title}<br/><span className="muted">{res.location}</span></>}</div>}</div></section>
}

function Receiving({d,done}){const[f,setF]=useState({seller_id:'',box_code:'',notes:''}),[err,setErr]=useState('');async function save(){try{await api('/api/ops',{method:'POST',body:JSON.stringify({action:'CREATE_BOX',...f})});setF({seller_id:'',box_code:'',notes:''});setErr('');done('Короб принят')}catch(e){setErr(e.message)}}return <section className="card"><h3>Приёмка</h3>{!(d.sellers||[]).length&&<div className="notice danger">Сначала добавь клиента во вкладке «Клиенты».</div>}<div className="formgrid"><select value={f.seller_id} onChange={e=>setF({...f,seller_id:e.target.value})}><option value="">Клиент</option>{(d.sellers||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={f.box_code} placeholder="Код короба / скан" onChange={e=>setF({...f,box_code:e.target.value})} onKeyDown={e=>e.key==='Enter'&&save()}/><input value={f.notes} placeholder="Комментарий" onChange={e=>setF({...f,notes:e.target.value})}/>{err&&<div className="notice danger">{err}</div>}<button className="btn primary" onClick={save}>Принять короб</button></div></section>}

function Boxes({d,rows,q,setQ,open}){return <section className="card"><div className="toolbar"><input value={q} placeholder="Поиск по коробу, клиенту, ячейке" onChange={e=>setQ(e.target.value)}/></div><div className="tablewrap"><table className="table"><thead><tr><th>Короб</th><th>Клиент</th><th>Зона</th><th>Ячейка</th><th>Ед.</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.box_code}</b></td><td>{x.seller_name}</td><td><span className="badge">{x.zone_name}</span></td><td>{x.cell_code||'—'}</td><td>{x.item_qty||0}</td><td><button className="btn" onClick={()=>open({kind:'item',id:x.id})}>+ SKU</button> <button className="btn" onClick={()=>open({kind:'move',id:x.id})}>Переместить</button></td></tr>)}</tbody></table></div></section>}

function Products({d,done}){const[f,setF]=useState({seller_id:'',sku:'',name:'',barcode:'',vendor:''});async function save(){try{await api('/api/ops',{method:'POST',body:JSON.stringify({action:'CREATE_PRODUCT',...f})});setF({seller_id:'',sku:'',name:'',barcode:'',vendor:''});done('SKU добавлен')}catch(e){alert(e.message)}}return <section className="card"><h3>Товары</h3><div className="toolbar"><select value={f.seller_id} onChange={e=>setF({...f,seller_id:e.target.value})}><option value="">Клиент</option>{(d.sellers||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={f.sku} placeholder="SKU" onChange={e=>setF({...f,sku:e.target.value})}/><input value={f.name} placeholder="Название" onChange={e=>setF({...f,name:e.target.value})}/><input value={f.barcode} placeholder="Штрихкод" onChange={e=>setF({...f,barcode:e.target.value})}/><button className="btn primary" onClick={save}>Добавить</button></div><div className="tablewrap"><table className="table"><thead><tr><th>SKU</th><th>Название</th><th>Клиент</th><th>Штрихкод</th></tr></thead><tbody>{(d.products||[]).map(p=><tr key={p.id}><td>{p.sku}</td><td>{p.name}</td><td>{p.seller_name}</td><td>{p.wb_barcode||'—'}</td></tr>)}</tbody></table></div></section>}

function Clients({d,done}){const[f,setF]=useState({name:'',contact:'',phone:'',email:''});async function save(){try{await api('/api/ops',{method:'POST',body:JSON.stringify({action:'CREATE_SELLER',...f})});setF({name:'',contact:'',phone:'',email:''});done('Клиент добавлен')}catch(e){alert(e.message)}}return <section className="card"><h3>Клиенты</h3><div className="toolbar"><input value={f.name} placeholder="Название клиента" onChange={e=>setF({...f,name:e.target.value})}/><input value={f.contact} placeholder="Контакт" onChange={e=>setF({...f,contact:e.target.value})}/><input value={f.phone} placeholder="Телефон" onChange={e=>setF({...f,phone:e.target.value})}/><button className="btn primary" onClick={save}>Добавить</button></div><div className="tablewrap"><table className="table"><thead><tr><th>Название</th><th>Контакт</th><th>Телефон</th><th>Email</th></tr></thead><tbody>{(d.sellers||[]).map(s=><tr key={s.id}><td><b>{s.name}</b></td><td>{s.contact_name||'—'}</td><td>{s.phone||'—'}</td><td>{s.email||'—'}</td></tr>)}</tbody></table></div></section>}

function Orders({d,done}){const [selected,setSelected]=useState(null);const order=(d.orders||[]).find(o=>o.id===selected);const items=(d.orderItems||[]).filter(i=>i.order_id===selected);return <div className="cards"><section className="card"><div className="top"><h3>FBS заказы</h3></div><div className="tablewrap"><table className="table"><thead><tr><th>Заказ</th><th>Клиент</th><th>Статус</th><th>Дедлайн</th></tr></thead><tbody>{(d.orders||[]).map(o=><tr key={o.id} onClick={()=>setSelected(o.id)} style={{cursor:'pointer'}}><td><b>{o.order_no}</b></td><td>{o.seller_name}</td><td><span className="badge">{o.status}</span></td><td>{o.deadline?new Date(o.deadline).toLocaleString():'—'}</td></tr>)}</tbody></table></div></section>{order&&<section className="card"><h3>{order.order_no}</h3><div className="muted">{order.seller_name} · {order.status}</div>{items.map(i=><PickLine key={i.id} item={i} d={d} done={done}/>)}<div className="actions" style={{marginTop:12}}>{order.status==='PICKED'&&<button className="btn" onClick={async()=>{await api('/api/ops',{method:'POST',body:JSON.stringify({action:'ORDER_PACKED',order_id:order.id})});done('Заказ передан в Packing')}}>Начать Packing</button>}{order.status==='PACKING'&&<button className="btn primary" onClick={async()=>{await api('/api/ops',{method:'POST',body:JSON.stringify({action:'ORDER_READY',order_id:order.id})});done('Заказ готов к отгрузке')}}>Готов к отгрузке</button>}{order.status==='READY'&&<button className="btn primary" onClick={async()=>{await api('/api/ops',{method:'POST',body:JSON.stringify({action:'ORDER_SHIPPED',order_id:order.id})});done('Заказ отгружен')}}>Отгрузить</button>}</div></section>}</div>}

function PickLine({item,d,done}){const [box,setBox]=useState(''),[qty,setQty]=useState(1);const candidates=(d.boxItems||[]).filter(x=>x.product_id===item.product_id&&x.qty>0);const left=Math.max(0,item.qty-item.picked_qty);async function pick(){try{await api('/api/ops',{method:'POST',body:JSON.stringify({action:'PICK_ITEM',order_item_id:item.id,box_id:box,qty:Number(qty)})});done('Позиция собрана')}catch(e){alert(e.message)}}return <div className="step" style={{display:'block',marginTop:8}}><b>{item.sku} — {item.product_name}</b><div className="muted">Нужно {item.qty} · собрано {item.picked_qty} · осталось {left}</div>{left>0&&<div className="toolbar" style={{marginTop:6}}><select value={box} onChange={e=>setBox(e.target.value)}><option value="">Короб-источник</option>{candidates.map(c=><option key={c.box_id} value={c.box_id}>{c.box_code} · {c.cell_code||'без ячейки'} · {c.qty} шт.</option>)}</select><input type="number" min="1" max={left} value={qty} onChange={e=>setQty(e.target.value)}/><button className="btn primary" disabled={!box} onClick={pick}>Подтвердить Picking</button></div>}</div>}

function Devices({d,done}){const [f,setF]=useState({device_type:'TSD',label:'',device_code:''});async function reg(){try{await api('/api/ops',{method:'POST',body:JSON.stringify({action:'REGISTER_DEVICE',...f,platform:navigator.platform,user_agent:navigator.userAgent})});done('Устройство зарегистрировано')}catch(e){alert(e.message)}}return <section className="card"><h3>Подключение устройств</h3><div className="notice">Для ТСД выбери режим HID/Keyboard и суффикс Enter. Для телефона регистрация нужна для журнала операций; камера запускается во вкладке «Скан».</div><div className="toolbar"><select value={f.device_type} onChange={e=>setF({...f,device_type:e.target.value})}><option>TSD</option><option>PHONE</option><option>TABLET</option></select><input value={f.label} placeholder="Название: ТСД-1 / iPhone кладовщика" onChange={e=>setF({...f,label:e.target.value})}/><input value={f.device_code} placeholder="Код устройства (необязательно)" onChange={e=>setF({...f,device_code:e.target.value})}/><button className="btn primary" onClick={reg}>Зарегистрировать</button></div><div className="tablewrap"><table className="table"><thead><tr><th>Код</th><th>Тип</th><th>Название</th><th>Активно</th></tr></thead><tbody>{(d.devices||[]).map(x=><tr key={x.id}><td>{x.device_code}</td><td>{x.device_type}</td><td>{x.label||'—'}</td><td>{x.active?'Да':'Нет'}</td></tr>)}</tbody></table></div></section>}

function Users({d,done}){const [f,setF]=useState({name:'',email:'',password:'',role:'RECEIVER'});async function save(){try{await api('/api/ops',{method:'POST',body:JSON.stringify({action:'CREATE_USER',...f})});setF({name:'',email:'',password:'',role:'RECEIVER'});done('Сотрудник создан')}catch(e){alert(e.message)}}return <section className="card"><h3>Сотрудники и роли</h3><div className="toolbar"><input value={f.name} placeholder="Имя" onChange={e=>setF({...f,name:e.target.value})}/><input value={f.email} placeholder="Email" onChange={e=>setF({...f,email:e.target.value})}/><input value={f.password} type="password" placeholder="Пароль 8+" onChange={e=>setF({...f,password:e.target.value})}/><select value={f.role} onChange={e=>setF({...f,role:e.target.value})}>{['ADMIN','MANAGER','RECEIVER','PICKER','PACKER','SHIPPER','VIEWER'].map(r=><option key={r}>{r}</option>)}</select><button className="btn primary" onClick={save}>Создать</button></div><div className="tablewrap"><table className="table"><thead><tr><th>Имя</th><th>Email</th><th>Роль</th><th>Статус</th></tr></thead><tbody>{(d.users||[]).map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.active?'Активен':'Отключен'}</td></tr>)}</tbody></table></div></section>}

function Audit({d}){return <section className="card"><h3>Журнал операций</h3><div className="tablewrap"><table className="table"><thead><tr><th>Дата</th><th>Пользователь</th><th>Действие</th><th>Объект</th></tr></thead><tbody>{(d.audit||[]).map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString()}</td><td>{a.user_name||'system'}</td><td>{a.action}</td><td>{a.entity_type||'—'}</td></tr>)}</tbody></table></div></section>}

function BoxModal({spec,d,close,done}){const [f,setF]=useState({});async function save(){try{if(spec.kind==='move'){const [target_type,target_id]=String(f.target||'').split(':');await api('/api/ops',{method:'POST',body:JSON.stringify({action:'MOVE_BOX',box_id:spec.id,target_type,target_id,reason:f.reason||'Перемещение'})});done('Короб перемещён')}else{await api('/api/ops',{method:'POST',body:JSON.stringify({action:'ADD_BOX_ITEM',box_id:spec.id,product_id:f.product_id,qty:Number(f.qty||1)})});done('SKU добавлен')}}catch(e){alert(e.message)}}return <div className="modalbg"><div className="modal"><h2>{spec.kind==='move'?'Перемещение короба':'Добавить SKU'}</h2><div className="formgrid">{spec.kind==='move'?<><select onChange={e=>setF({...f,target:e.target.value})}><option value="">Куда</option>{(d.zones||[]).map(z=><option key={z.id} value={'zone:'+z.id}>Зона: {z.name}</option>)}{(d.cells||[]).map(c=><option key={c.id} value={'cell:'+c.id}>Ячейка: {c.code}</option>)}</select><input placeholder="Причина" onChange={e=>setF({...f,reason:e.target.value})}/></>:<><select onChange={e=>setF({...f,product_id:e.target.value})}><option value="">Товар</option>{(d.products||[]).map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select><input type="number" min="1" defaultValue="1" onChange={e=>setF({...f,qty:e.target.value})}/></>}<button className="btn primary" onClick={save}>Подтвердить</button><button className="btn" onClick={close}>Отмена</button></div></div></div>}
