'use client';
import {useEffect,useRef,useState} from 'react';

const MOBILE=['Обзор','Скан','Приёмка','Короба','Заказы'];
const ROLE_TABS={
 ADMIN:['Обзор','Скан','Приёмка','Короба','Товары','Клиенты','Заказы','Устройства','Сотрудники','Журнал'],
 MANAGER:['Обзор','Скан','Приёмка','Короба','Товары','Клиенты','Заказы','Устройства','Журнал'],
 RECEIVER:['Обзор','Скан','Приёмка','Короба','Товары','Устройства'],
 PICKER:['Обзор','Скан','Короба','Заказы','Устройства'],
 PACKER:['Обзор','Скан','Короба','Заказы','Устройства'],
 SHIPPER:['Обзор','Скан','Заказы','Устройства'],
 VIEWER:['Обзор','Скан','Короба','Товары','Заказы']
};
async function api(url,opts={}){const r=await fetch(url,{cache:'no-store',headers:{'content-type':'application/json',...(opts.headers||{})},...opts});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Ошибка');return j}
const ops=(body)=>api('/api/ops',{method:'POST',body:JSON.stringify(body)});

export default function WmsAppV3(){
 const[state,setState]=useState({loading:true}),[tab,setTab]=useState('Обзор'),[toast,setToast]=useState(''),[modal,setModal]=useState(null),[q,setQ]=useState('');
 async function load(){try{setState({loading:true});setState(await api('/api/bootstrap'))}catch(e){setState({loading:false,error:e.message})}}
 useEffect(()=>{load()},[]);
 async function refresh(msg){await load();if(msg){setToast(msg);setTimeout(()=>setToast(''),2000)}}
 if(state.loading)return <div className="content">Загрузка WMS…</div>;
 if(state.error)return <div className="content"><div className="notice danger">{state.error}</div><button className="btn" onClick={load}>Повторить</button></div>;
 if(state.setupRequired)return <Auth setup done={load}/>;
 if(!state.user)return <Auth done={load}/>;
 const d=state.data||{},tabs=ROLE_TABS[state.user.role]||ROLE_TABS.VIEWER,visible=tabs.includes(tab)?tab:'Обзор';
 const boxes=(d.boxes||[]).filter(x=>`${x.box_code} ${x.seller_name||''} ${x.zone_name||''} ${x.cell_code||''}`.toLowerCase().includes(q.toLowerCase()));
 return <div className="app"><aside className="side"><div className="brand">FULFILLMENT <span>WMS</span></div><div className="nav">{tabs.map(x=><button key={x} className={visible===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="device" style={{position:'absolute',bottom:20,left:22}}>● ONLINE<br/>{state.user.name}<br/>{state.user.role}</div></aside><main className="content"><div className="top"><div><div className="muted">FULFILLMENT CONTROL CENTER</div><h1>{visible}</h1><div className="muted">FBS · единая PostgreSQL база · ТСД + телефон</div></div><div className="actions"><button className="btn primary" onClick={()=>setTab('Скан')}>Сканировать</button><button className="btn" onClick={async()=>{await api('/api/auth/logout',{method:'POST'});load()}}>Выйти</button></div></div>{toast&&<div className="notice ok">{toast}</div>}<div className="grid4"><Metric n="Коробов" v={d.boxes?.length||0}/><Metric n="SKU" v={d.products?.length||0}/><Metric n="Заказов" v={d.orders?.length||0}/><Metric n="Клиентов" v={d.sellers?.length||0}/></div>{visible==='Обзор'&&<Overview d={d} setTab={setTab}/>} {visible==='Скан'&&<Scanner/>} {visible==='Приёмка'&&<Receiving d={d} done={refresh}/>} {visible==='Короба'&&<Boxes rows={boxes} q={q} setQ={setQ} open={setModal}/>} {visible==='Товары'&&<Products d={d} done={refresh}/>} {visible==='Клиенты'&&<Clients d={d} done={refresh}/>} {visible==='Заказы'&&<Orders d={d} role={state.user.role} done={refresh}/>} {visible==='Устройства'&&<Devices d={d} done={refresh}/>} {visible==='Сотрудники'&&<Users d={d} done={refresh}/>} {visible==='Журнал'&&<Audit d={d}/>}</main><nav className="mobilebar">{MOBILE.filter(x=>tabs.includes(x)).map(x=><button key={x} className={visible===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>{modal&&<BoxModal spec={modal} d={d} close={()=>setModal(null)} done={async m=>{setModal(null);await refresh(m)}}/>}</div>
}
function Metric({n,v}){return <div className="metric"><small>{n}</small><b>{v}</b></div>}
function Auth({setup,done}){const[f,setF]=useState({name:'',email:'',password:''}),[err,setErr]=useState('');async function go(){try{await api(setup?'/api/auth/setup':'/api/auth/login',{method:'POST',body:JSON.stringify(f)});done()}catch(e){setErr(e.message)}}return <div style={{maxWidth:420,margin:'70px auto',padding:16}}><div className="card"><h2>{setup?'Первичная настройка WMS':'Вход в WMS'}</h2>{setup&&<input placeholder="Имя администратора" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/>}<input placeholder="Email" inputMode="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input type="password" placeholder="Пароль" value={f.password} onChange={e=>setF({...f,password:e.target.value})} onKeyDown={e=>e.key==='Enter'&&go()}/>{err&&<div className="notice danger">{err}</div>}<button className="btn primary" style={{width:'100%'}} onClick={go}>{setup?'Создать администратора':'Войти'}</button></div></div>}
function Overview({d,setTab}){const stages=[['Приёмка','RCV'],['QC','QC'],['Сортировка','SRT'],['Хранение','STG'],['Picking','PCK'],['Packing','PAK'],['Готово','RDY'],['Отгрузка','SHP'],['Возвраты','RET']];return <div className="cards"><section className="card"><h3>Операционный поток</h3><div className="flow">{stages.map(([n,c])=><button className="step" key={c} onClick={()=>setTab(c==='RCV'?'Приёмка':['PCK','PAK','RDY','SHP'].includes(c)?'Заказы':'Короба')}><b>{n}</b><span className="muted">{(d.boxes||[]).filter(x=>x.zone_code===c).length} коробов</span></button>)}</div></section><section className="card"><h3>Быстрый старт</h3><button className="btn primary" style={{width:'100%',margin:'4px 0'}} onClick={()=>setTab('Скан')}>Скан-центр</button><button className="btn" style={{width:'100%',margin:'4px 0'}} onClick={()=>setTab('Приёмка')}>Приёмка</button><button className="btn" style={{width:'100%',margin:'4px 0'}} onClick={()=>setTab('Заказы')}>FBS заказы</button></section></div>}
function Scanner(){const[code,setCode]=useState(''),[res,setRes]=useState(null),[cam,setCam]=useState(false);const video=useRef(null),controls=useRef(null);async function lookup(v=code){const val=String(v||'').trim();if(!val)return;try{setRes(await api('/api/scan',{method:'POST',body:JSON.stringify({barcode:val})}));setCode('')}catch(e){setRes({error:e.message})}}useEffect(()=>{if(!cam)return;let stopped=false;async function start(){try{const {BrowserMultiFormatReader}=await import('@zxing/browser');const reader=new BrowserMultiFormatReader();controls.current=await reader.decodeFromVideoDevice(undefined,video.current,(result)=>{if(result&&!stopped){stopped=true;const text=result.getText();controls.current?.stop();setCam(false);lookup(text)}})}catch(e){setRes({error:'Камера: '+e.message});setCam(false)}}start();return()=>{stopped=true;controls.current?.stop()}},[cam]);return <section className="card"><h3>Скан-центр</h3><div className="notice">ТСД: HID/Keyboard + суффикс Enter. Телефон: ZXing использует заднюю камеру по HTTPS.</div><div className="scanbox"><input autoFocus value={code} placeholder="Короб / SKU / ячейка / заказ" onChange={e=>setCode(e.target.value)} onKeyDown={e=>e.key==='Enter'&&lookup()}/><div className="actions" style={{marginTop:8}}><button className="btn primary" onClick={()=>lookup()}>Распознать</button><button className="btn" onClick={()=>setCam(v=>!v)}>{cam?'Закрыть камеру':'Камера телефона'}</button></div>{cam&&<video ref={video} className="camera" playsInline muted/>}{res&&<div className={`notice ${res.error?'danger':'ok'}`} style={{marginTop:10}}>{res.error?res.error:<><b>{res.kind}: {res.code}</b><br/>{res.title}<br/><span className="muted">{res.location}</span></>}</div>}</div></section>}
function Receiving({d,done}){const[f,setF]=useState({seller_id:'',box_code:'',notes:''}),[err,setErr]=useState('');async function save(){try{await ops({action:'CREATE_BOX',...f});setF({seller_id:'',box_code:'',notes:''});setErr('');done('Короб принят')}catch(e){setErr(e.message)}}return <section className="card"><h3>Приёмка короба</h3>{!(d.sellers||[]).length&&<div className="notice danger">Сначала добавь клиента.</div>}<div className="formgrid"><select value={f.seller_id} onChange={e=>setF({...f,seller_id:e.target.value})}><option value="">Клиент</option>{(d.sellers||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={f.box_code} placeholder="Код короба / скан" onChange={e=>setF({...f,box_code:e.target.value})} onKeyDown={e=>e.key==='Enter'&&save()}/><input value={f.notes} placeholder="Комментарий" onChange={e=>setF({...f,notes:e.target.value})}/>{err&&<div className="notice danger">{err}</div>}<button className="btn primary" onClick={save}>Принять в зону «Приёмка»</button></div></section>}
function Boxes({rows,q,setQ,open}){return <section className="card"><div className="toolbar"><input value={q} placeholder="Короб, клиент, ячейка…" onChange={e=>setQ(e.target.value)}/></div><Table heads={['Короб','Клиент','Зона','Ячейка','Ед.','']} rows={rows.map(x=>[<b>{x.box_code}</b>,x.seller_name,<span className="badge">{x.zone_name}</span>,x.cell_code||'—',x.item_qty||0,<><button className="btn" onClick={()=>open({kind:'item',id:x.id})}>+ SKU</button> <button className="btn" onClick={()=>open({kind:'move',id:x.id})}>Переместить</button></>])}/></section>}
function Products({d,done}){const[f,setF]=useState({seller_id:'',sku:'',name:'',barcode:'',vendor:''}),[err,setErr]=useState('');async function save(){try{await ops({action:'CREATE_PRODUCT',...f});setF({seller_id:'',sku:'',name:'',barcode:'',vendor:''});setErr('');done('SKU добавлен')}catch(e){setErr(e.message)}}return <section className="card"><h3>Товары</h3><div className="toolbar"><select value={f.seller_id} onChange={e=>setF({...f,seller_id:e.target.value})}><option value="">Клиент</option>{(d.sellers||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={f.sku} placeholder="SKU" onChange={e=>setF({...f,sku:e.target.value})}/><input value={f.name} placeholder="Название" onChange={e=>setF({...f,name:e.target.value})}/><input value={f.barcode} placeholder="Штрихкод" onChange={e=>setF({...f,barcode:e.target.value})}/><button className="btn primary" onClick={save}>Добавить</button></div>{err&&<div className="notice danger">{err}</div>}<Table heads={['SKU','Название','Клиент','Штрихкод']} rows={(d.products||[]).map(p=>[p.sku,p.name,p.seller_name,p.wb_barcode||'—'])}/></section>}
function Clients({d,done}){const[f,setF]=useState({name:'',contact:'',phone:'',email:''}),[err,setErr]=useState('');async function save(){try{await ops({action:'CREATE_SELLER',...f});setF({name:'',contact:'',phone:'',email:''});setErr('');done('Клиент добавлен')}catch(e){setErr(e.message)}}return <section className="card"><h3>Клиенты / владельцы товара</h3><div className="toolbar"><input value={f.name} placeholder="Название" onChange={e=>setF({...f,name:e.target.value})}/><input value={f.contact} placeholder="Контакт" onChange={e=>setF({...f,contact:e.target.value})}/><input value={f.phone} placeholder="Телефон" onChange={e=>setF({...f,phone:e.target.value})}/><input value={f.email} placeholder="Email" onChange={e=>setF({...f,email:e.target.value})}/><button className="btn primary" onClick={save}>Добавить</button></div>{err&&<div className="notice danger">{err}</div>}<Table heads={['Клиент','Контакт','Телефон','Email']} rows={(d.sellers||[]).map(s=>[s.name,s.contact_name||'—',s.phone||'—',s.email||'—'])}/></section>}
function Orders({d,role,done}){const[selected,setSelected]=useState(null);const order=(d.orders||[]).find(o=>o.id===selected);const items=(d.orderItems||[]).filter(i=>i.order_id===selected);return <div className="cards"><section className="card"><div className="top"><h3>FBS заказы</h3>{['ADMIN','MANAGER'].includes(role)&&<OrderCreate d={d} done={done}/>}</div><Table heads={['Заказ','Клиент','Статус','Дедлайн']} rows={(d.orders||[]).map(o=>[<button className="btn" onClick={()=>setSelected(o.id)}><b>{o.order_no}</b></button>,o.seller_name,<span className="badge">{o.status}</span>,o.deadline?new Date(o.deadline).toLocaleString():'—'])}/></section>{order&&<section className="card"><h3>{order.order_no}</h3><div className="muted">{order.seller_name} · {order.status}</div>{items.map(i=><PickLine key={i.id} item={i} d={d} role={role} done={done}/>)}<div className="actions" style={{marginTop:12}}>{order.status==='PICKED'&&['ADMIN','MANAGER','PACKER'].includes(role)&&<button className="btn primary" onClick={async()=>{await ops({action:'ORDER_PACKED',order_id:order.id});done('Заказ упакован')}}>Подтвердить упаковку</button>}{order.status==='PACKED'&&['ADMIN','MANAGER','PACKER'].includes(role)&&<button className="btn primary" onClick={async()=>{await ops({action:'ORDER_READY',order_id:order.id});done('Готов к отгрузке')}}>Готов к отгрузке</button>}{order.status==='READY'&&['ADMIN','MANAGER','PACKER','SHIPPER'].includes(role)&&<button className="btn primary" onClick={async()=>{await ops({action:'ORDER_SHIPPED',order_id:order.id});done('Заказ отгружен')}}>Отгрузить</button>}</div></section>}</div>}
function OrderCreate({d,done}){const[open,setOpen]=useState(false),[f,setF]=useState({seller_id:'',order_no:'',deadline:'',priority:'NORMAL'}),[line,setLine]=useState({product_id:'',qty:1}),[items,setItems]=useState([]),[err,setErr]=useState('');function add(){if(!line.product_id||Number(line.qty)<=0)return;const p=(d.products||[]).find(x=>x.id===line.product_id);setItems([...items,{product_id:line.product_id,qty:Number(line.qty),label:p?`${p.sku} — ${p.name}`:line.product_id}]);setLine({product_id:'',qty:1})}async function save(){try{await ops({action:'CREATE_ORDER',seller_id:f.seller_id,order_no:f.order_no,deadline:f.deadline||null,priority:f.priority,items:items.map(({product_id,qty})=>({product_id,qty}))});setOpen(false);setItems([]);setErr('');done('Заказ создан')}catch(e){setErr(e.message)}}if(!open)return <button className="btn primary" onClick={()=>setOpen(true)}>+ Новый заказ</button>;return <div className="modalbg"><div className="modal"><h2>Новый FBS заказ</h2><div className="formgrid"><select value={f.seller_id} onChange={e=>setF({...f,seller_id:e.target.value})}><option value="">Клиент</option>{(d.sellers||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={f.order_no} placeholder="Номер заказа (необязательно)" onChange={e=>setF({...f,order_no:e.target.value})}/><input type="datetime-local" value={f.deadline} onChange={e=>setF({...f,deadline:e.target.value})}/><select value={line.product_id} onChange={e=>setLine({...line,product_id:e.target.value})}><option value="">SKU</option>{(d.products||[]).filter(p=>!f.seller_id||p.seller_id===f.seller_id).map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select><input type="number" min="1" value={line.qty} onChange={e=>setLine({...line,qty:e.target.value})}/><button className="btn" onClick={add}>Добавить позицию</button>{items.map((i,n)=><div className="notice" key={n}>{i.label} × {i.qty}</div>)}{err&&<div className="notice danger">{err}</div>}<button className="btn primary" disabled={!f.seller_id||!items.length} onClick={save}>Создать заказ</button><button className="btn" onClick={()=>setOpen(false)}>Отмена</button></div></div></div>}
function PickLine({item,d,role,done}){const[box,setBox]=useState(''),[qty,setQty]=useState(1);const left=Math.max(0,item.qty-item.picked_qty),candidates=(d.boxItems||[]).filter(x=>x.product_id===item.product_id&&x.qty>0);async function pick(){try{await ops({action:'PICK_ITEM',order_item_id:item.id,box_id:box,qty:Number(qty)});done('Позиция собрана')}catch(e){alert(e.message)}}return <div className="step" style={{display:'block',marginTop:8}}><b>{item.sku} — {item.product_name}</b><div className="muted">Нужно {item.qty} · собрано {item.picked_qty} · осталось {left}</div>{left>0&&['ADMIN','MANAGER','PICKER'].includes(role)&&<div className="toolbar"><select value={box} onChange={e=>setBox(e.target.value)}><option value="">Короб-источник</option>{candidates.map(c=><option key={c.box_id} value={c.box_id}>{c.box_code} · {c.cell_code||'без ячейки'} · {c.qty} шт.</option>)}</select><input type="number" min="1" max={left} value={qty} onChange={e=>setQty(e.target.value)}/><button className="btn primary" disabled={!box} onClick={pick}>Pick</button></div>}</div>}
function Devices({d,done}){const[f,setF]=useState({device_type:'TSD',label:'',device_code:''}),[err,setErr]=useState('');async function reg(){try{const r=await ops({action:'REGISTER_DEVICE',...f,platform:navigator.platform,user_agent:navigator.userAgent});setErr('');done('Устройство: '+r.device_code)}catch(e){setErr(e.message)}}return <section className="card"><h3>Устройства</h3><div className="notice">ТСД: HID/Keyboard + Enter. Телефон: разреши камеру в браузере. Зарегистрируй устройство, чтобы привязать операции к рабочему месту.</div><div className="toolbar"><select value={f.device_type} onChange={e=>setF({...f,device_type:e.target.value})}><option>TSD</option><option>PHONE</option><option>TABLET</option></select><input value={f.label} placeholder="Название устройства" onChange={e=>setF({...f,label:e.target.value})}/><input value={f.device_code} placeholder="Код (необязательно)" onChange={e=>setF({...f,device_code:e.target.value})}/><button className="btn primary" onClick={reg}>Подключить</button></div>{err&&<div className="notice danger">{err}</div>}<Table heads={['Код','Тип','Название','Статус']} rows={(d.devices||[]).map(x=>[x.device_code,x.device_type,x.label||'—',x.active?'Активно':'Отключено'])}/></section>}
function Users({d,done}){const[f,setF]=useState({name:'',email:'',password:'',role:'RECEIVER'}),[err,setErr]=useState('');async function save(){try{await ops({action:'CREATE_USER',...f});setF({name:'',email:'',password:'',role:'RECEIVER'});setErr('');done('Сотрудник создан')}catch(e){setErr(e.message)}}return <section className="card"><h3>Сотрудники и роли</h3><div className="toolbar"><input value={f.name} placeholder="Имя" onChange={e=>setF({...f,name:e.target.value})}/><input value={f.email} placeholder="Email" onChange={e=>setF({...f,email:e.target.value})}/><input value={f.password} type="password" placeholder="Пароль 8+" onChange={e=>setF({...f,password:e.target.value})}/><select value={f.role} onChange={e=>setF({...f,role:e.target.value})}>{Object.keys(ROLE_TABS).map(r=><option key={r}>{r}</option>)}</select><button className="btn primary" onClick={save}>Создать</button></div>{err&&<div className="notice danger">{err}</div>}<Table heads={['Имя','Email','Роль','Статус']} rows={(d.users||[]).map(u=>[u.name,u.email,u.role,u.active?'Активен':'Отключён'])}/></section>}
function Audit({d}){return <section className="card"><h3>Журнал операций</h3><Table heads={['Дата','Пользователь','Действие','Объект']} rows={(d.audit||[]).map(a=>[new Date(a.created_at).toLocaleString(),a.user_name||'system',a.action,a.entity_type||'—'])}/></section>}
function Table({heads,rows}){return <div className="tablewrap"><table className="table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function BoxModal({spec,d,close,done}){const[f,setF]=useState({}),[err,setErr]=useState('');async function save(){try{if(spec.kind==='move'){const[target_type,target_id]=String(f.target||'').split(':');await ops({action:'MOVE_BOX',box_id:spec.id,target_type,target_id,reason:f.reason||'Перемещение'});done('Короб перемещён')}else{await ops({action:'ADD_BOX_ITEM',box_id:spec.id,product_id:f.product_id,qty:Number(f.qty||1)});done('SKU добавлен в короб')}}catch(e){setErr(e.message)}}return <div className="modalbg"><div className="modal"><h2>{spec.kind==='move'?'Перемещение короба':'Добавить SKU'}</h2><div className="formgrid">{spec.kind==='move'?<><select onChange={e=>setF({...f,target:e.target.value})}><option value="">Куда</option>{(d.zones||[]).map(z=><option key={z.id} value={'zone:'+z.id}>Зона: {z.name}</option>)}{(d.cells||[]).map(c=><option key={c.id} value={'cell:'+c.id}>Ячейка: {c.code}</option>)}</select><input placeholder="Причина" onChange={e=>setF({...f,reason:e.target.value})}/></>:<><select onChange={e=>setF({...f,product_id:e.target.value})}><option value="">Товар</option>{(d.products||[]).map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select><input type="number" min="1" defaultValue="1" onChange={e=>setF({...f,qty:e.target.value})}/></>}{err&&<div className="notice danger">{err}</div>}<button className="btn primary" onClick={save}>Подтвердить</button><button className="btn" onClick={close}>Отмена</button></div></div></div>}
